# syntax=docker/dockerfile:1

# =========================================================
# Stage 1 - Build React application
# =========================================================
FROM node:24-bookworm-slim AS build

WORKDIR /app

# Use the built-in non-root user
RUN chown node:node /app

USER node

# Copy dependency files first for Docker layer caching
COPY --chown=node:node /frontend/package.json frontend/package-lock.json ./

# Install dependencies required to build React
RUN npm ci \
    && npm cache clean --force

# Copy frontend source code
COPY --chown=node:node /frontend .

# Build production static files
RUN npm run build


# =========================================================
# Stage 2 - Serve static files with Nginx
# =========================================================
FROM nginxinc/nginx-unprivileged:stable-alpine

# Remove default Nginx static content
RUN rm -rf /usr/share/nginx/html/*

# Copy only compiled React files from build stage
COPY --from=build /app/dist /usr/share/nginx/html

# Nginx unprivileged image listens on 8080
EXPOSE 8080

CMD ["npm", "run", "dev"]