# syntax=docker/dockerfile:1

FROM node:24-bookworm-slim

ENV NODE_ENV=dev

WORKDIR /app

# Copy dependency files
COPY frontend/package.json frontend/package-lock.json ./

# Install dependencies while building the image
RUN npm ci \
    && npm cache clean --force

# Copy application
COPY frontend/ .

# Give the application directory to the non-root user
RUN chown -R node:node /app

# Drop root privileges
USER node

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]